name: "Build, test and deploy to GitHub Pages Angular Project"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend/rps-101
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: frontend/rps-101/dist

  deploy:
    name: Push to Github Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        #Use build artifact
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist
      #Deploy build folder (dist/rps-101-23) to gh-pages branch GitHub for Pages)
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          branch: gh-pages
          folder: deploy_dist/rps-101
