name: "Build and deploy to GitHub Pages Angular Project"

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend/rps-101
jobs:
  deploy_ghpages:
    name: Push to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npx ng build --base-href /rps-101-23/
      - name: Copy index to 404 
        run: cp ./dist/rps-101/index.html ./dist/rps-101/404.html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: frontend/rps-101/dist/rps-101
          clean: true
          single-commit: true
